export default [
  { name: 'Cart', icon: 'mdi-cart' },
  { name: 'Cart Outline', icon: 'mdi-cart-outline' },
  { name: 'Cart Variant', icon: 'mdi-cart-variant' },
  { name: 'Cellphone', icon: 'mdi-cellphone' },
  { name: 'Volume High', icon: 'mdi-volume-high' },
  { name: 'Volume Low', icon: 'mdi-volume-low' },
  { name: 'Volume Minus', icon: 'mdi-volume-minus' },
  { name: 'Volume Plus', icon: 'mdi-volume-plus' },
  { name: 'Volume Off', icon: 'mdi-volume-off' },
  { name: 'Signal', icon: 'mdi-signal' },
  { name: 'Camera', icon: 'mdi-camera' },
  { name: 'Home', icon: 'mdi-home' },
  { name: 'Home Outline', icon: 'mdi-home-outline' },
  { name: 'Cog Outline', icon: 'mdi-cog-outline' },
  { name: 'Cog', icon: 'mdi-cog' },
  { name: 'Cog Off', icon: 'mdi-cog-off' },
  { name: 'Cog Off Outline', icon: 'mdi-cog-off-outline' },
  { name: 'Apps', icon: 'mdi-apps' },
  { name: 'Apps Box', icon: 'mdi-apps-box' },
  { name: 'Gauge', icon: 'mdi-gauge' },
  { name: 'Robot', icon: 'mdi-robot' },
  { name: 'Account', icon: 'mdi-account' },
  { name: 'Account Multiple', icon: 'mdi-account-multiple' },
  { name: 'Account Box Multiple', icon: 'mdi-account-box-multiple' },
  { name: 'Account Box', icon: 'mdi-account-box' },
  {
    name: 'Account Box Multiple Outline',
    icon: 'mdi-account-box-multiple-outline',
  },
  { name: 'Account Box Outline', icon: 'mdi-account-box-outline' },
  { name: 'Badge Account Horizontal', icon: 'mdi-badge-account-horizontal' },
  {
    name: 'Badge Account Horizontal Outline',
    icon: 'mdi-badge-account-horizontal-outline',
  },
  { name: 'Image Filter Drama', icon: 'mdi-image-filter-drama' },
  { name: 'Cloud', icon: 'mdi-cloud' },
  { name: 'Cloud Download', icon: 'mdi-cloud-download' },
  { name: 'Cloud Check', icon: 'mdi-cloud-check' },
  { name: 'Cloud Alert', icon: 'mdi-cloud-alert' },
  { name: 'Cloud Sync', icon: 'mdi-cloud-sync' },
  { name: 'Cloud Search', icon: 'mdi-cloud-search' },
  { name: 'Cloud Outline', icon: 'mdi-cloud-outline' },
  { name: 'Cloud Download Outline', icon: 'mdi-cloud-download-outline' },
  { name: 'Cloud Check Outline', icon: 'mdi-cloud-check-outline' },
  { name: 'Cloud Sync Outline', icon: 'mdi-cloud-sync-outline' },
  { name: 'Cloud Search Outline', icon: 'mdi-cloud-search-outline' },
  { name: 'Cloud Upload Outline', icon: 'mdi-cloud-upload-outline' },
  { name: 'Upload', icon: 'mdi-upload' },
  { name: 'Clock Outline', icon: 'mdi-clock-outline' },
  { name: 'Clock', icon: 'mdi-clock' },
  { name: 'History', icon: 'mdi-history' },
  { name: 'Cached', icon: 'mdi-cached' },
  { name: 'Lock Open', icon: 'mdi-lock-open' },
  { name: 'Lock', icon: 'mdi-lock' },
  { name: 'Lock Open Outline', icon: 'mdi-lock-open-outline' },
  { name: 'Lock Outline', icon: 'mdi-lock-outline' },
  { name: 'Wifi', icon: 'mdi-wifi' },
  { name: 'Currency USD', icon: 'mdi-currency-usd' },
  { name: 'Currency CNY', icon: 'mdi-currency-cny' },
  { name: 'Gender Female', icon: 'mdi-gender-female' },
  { name: 'Gender Male', icon: 'mdi-gender-male' },
  { name: 'Gift', icon: 'mdi-gift' },
  { name: 'Gift Open', icon: 'mdi-gift-open' },
  { name: 'Gift Outline', icon: 'mdi-gift-outline' },
  { name: 'Gift Open Outline', icon: 'mdi-gift-open-outline' },
  { name: 'Package Variant Closed', icon: 'mdi-package-variant-closed' },
  { name: 'Package Variant', icon: 'mdi-package-variant' },
  { name: 'Google Downasaur', icon: 'mdi-google-downasaur' },
  { name: 'Apple', icon: 'mdi-apple' },
  { name: 'Compass', icon: 'mdi-compass' },
  { name: 'Compass Outline', icon: 'mdi-compass-outline' },
  { name: 'Map Marker', icon: 'mdi-map-marker' },
  { name: 'Map Marker Outline', icon: 'mdi-map-marker-outline' },
  { name: 'Message', icon: 'mdi-message' },
  { name: 'Message Outline', icon: 'mdi-message-outline' },
  { name: 'QR Code', icon: 'mdi-qrcode' },
  { name: 'QR Code Scan', icon: 'mdi-qrcode-scan' },
  { name: 'Printer', icon: 'mdi-printer' },
  { name: 'View Dashboard', icon: 'mdi-view-dashboard' },
  { name: 'View Dashboard Outline', icon: 'mdi-view-dashboard-outline' },
  { name: 'Storefront', icon: 'mdi-storefront' },
  { name: 'Storefront Outline', icon: 'mdi-storefront-outline' },
  { name: 'Tag', icon: 'mdi-tag' },
  { name: 'Tag Outline', icon: 'mdi-tag-outline' },
  { name: 'Tag Multiple', icon: 'mdi-tag-multiple' },
  { name: 'Tag Multiple Outline', icon: 'mdi-tag-multiple-outline' },
  { name: 'Thumb Up', icon: 'mdi-thumb-up' },
  { name: 'Thumb Down', icon: 'mdi-thumb-down' },
  { name: 'Thumb Up Outline', icon: 'mdi-thumb-up-outline' },
  { name: 'Thumb Down Outline', icon: 'mdi-thumb-down-outline' },
  { name: 'Connection', icon: 'mdi-connection' },
  { name: 'Source Branch', icon: 'mdi-source-branch' },
  { name: 'Export', icon: 'mdi-export' },
  { name: 'Reload', icon: 'mdi-reload' },
  { name: 'Calendar Blank', icon: 'mdi-calendar-blank' },
  { name: 'Calendar Blank Outline', icon: 'mdi-calendar-blank-outline' },
  { name: 'Share Variant', icon: 'mdi-share-variant' },
  { name: 'Share Variant Outline', icon: 'mdi-share-variant-outline' },
  { name: 'Image Size Select Actual', icon: 'mdi-image-size-select-actual' },
  { name: 'Resize Bottom Right', icon: 'mdi-resize-bottom-right' },
  { name: 'Console', icon: 'mdi-console' },
  { name: 'Folder Open Outline', icon: 'mdi-folder-open-outline' },
  { name: 'Parachute Outline', icon: 'mdi-parachute-outline' },
  { name: 'Face Man Profile', icon: 'mdi-face-man-profile' },

  // Navigation
  { name: 'Menu', icon: 'mdi-menu' },
  { name: 'Close', icon: 'mdi-close' },
  { name: 'Chevron Left', icon: 'mdi-chevron-left' },
  { name: 'Chevron Right', icon: 'mdi-chevron-right' },
  { name: 'Chevron Up', icon: 'mdi-chevron-up' },
  { name: 'Chevron Down', icon: 'mdi-chevron-down' },
  { name: 'Arrow Left', icon: 'mdi-arrow-left' },
  { name: 'Arrow Right', icon: 'mdi-arrow-right' },
  { name: 'Arrow Up', icon: 'mdi-arrow-up' },
  { name: 'Arrow Down', icon: 'mdi-arrow-down' },

  // Actions
  { name: 'Plus', icon: 'mdi-plus' },
  { name: 'Minus', icon: 'mdi-minus' },
  { name: 'Delete', icon: 'mdi-delete' },
  { name: 'Edit', icon: 'mdi-pencil' },
  { name: 'Save', icon: 'mdi-content-save' },
  { name: 'Refresh', icon: 'mdi-refresh' },
  { name: 'Search', icon: 'mdi-magnify' },
  { name: 'Sort', icon: 'mdi-sort' },

  // Communication
  { name: 'Email', icon: 'mdi-email' },
  { name: 'Phone', icon: 'mdi-phone' },
  { name: 'Video', icon: 'mdi-video' },
  { name: 'Chat', icon: 'mdi-chat' },

  // Media
  { name: 'Play', icon: 'mdi-play' },
  { name: 'Pause', icon: 'mdi-pause' },
  { name: 'Stop', icon: 'mdi-stop' },
  { name: 'Fast Forward', icon: 'mdi-fast-forward' },
  { name: 'Rewind', icon: 'mdi-rewind' },

  // Files and Folders
  { name: 'File', icon: 'mdi-file' },
  { name: 'Folder', icon: 'mdi-folder' },
  { name: 'Download', icon: 'mdi-download' },

  // Misc
  { name: 'Star', icon: 'mdi-star' },
  { name: 'Heart', icon: 'mdi-heart' },
  { name: 'Bell', icon: 'mdi-bell' },
  { name: 'Help', icon: 'mdi-help-circle' },
  { name: 'Information', icon: 'mdi-information' },
  { name: 'Warning', icon: 'mdi-alert' },
  { name: 'Error', icon: 'mdi-alert-circle' },
  { name: 'Success', icon: 'mdi-check-circle' },

  // Social Media
  { name: 'Facebook', icon: 'mdi-facebook' },
  { name: 'Twitter', icon: 'mdi-twitter' },
  { name: 'Instagram', icon: 'mdi-instagram' },
  { name: 'LinkedIn', icon: 'mdi-linkedin' },
  { name: 'YouTube', icon: 'mdi-youtube' },

  // E-commerce
  { name: 'Shopping', icon: 'mdi-shopping' },
  { name: 'Credit Card', icon: 'mdi-credit-card' },
  { name: 'Cash', icon: 'mdi-cash' },
  { name: 'Sale', icon: 'mdi-sale' },
  { name: 'Barcode', icon: 'mdi-barcode' },

  // Weather
  { name: 'Weather Sunny', icon: 'mdi-weather-sunny' },
  { name: 'Weather Cloudy', icon: 'mdi-weather-cloudy' },
  { name: 'Weather Rainy', icon: 'mdi-weather-rainy' },
  { name: 'Weather Snowy', icon: 'mdi-weather-snowy' },
  { name: 'Weather Night', icon: 'mdi-weather-night' },

  // Devices and Hardware
  { name: 'Laptop', icon: 'mdi-laptop' },
  { name: 'Tablet', icon: 'mdi-tablet' },
  { name: 'Monitor', icon: 'mdi-monitor' },
  { name: 'Keyboard', icon: 'mdi-keyboard' },
  { name: 'Mouse', icon: 'mdi-mouse' },

  // Application and Development
  { name: 'Code Tags', icon: 'mdi-code-tags' },
  { name: 'Database', icon: 'mdi-database' },
  { name: 'Server', icon: 'mdi-server' },
  { name: 'Language HTML', icon: 'mdi-language-html5' },
  { name: 'Language CSS', icon: 'mdi-language-css3' },
  { name: 'Language JavaScript', icon: 'mdi-language-javascript' },

  // File Types
  { name: 'File Word', icon: 'mdi-file-word' },
  { name: 'File Excel', icon: 'mdi-file-excel' },
  { name: 'File Image', icon: 'mdi-file-image' },
  { name: 'File Video', icon: 'mdi-file-video' },
  { name: 'File Music', icon: 'mdi-file-music' },

  // User Interface
  { name: 'Checkbox Marked', icon: 'mdi-checkbox-marked' },
  { name: 'Checkbox Blank', icon: 'mdi-checkbox-blank-outline' },
  { name: 'Radiobox Marked', icon: 'mdi-radiobox-marked' },
  { name: 'Radiobox Blank', icon: 'mdi-radiobox-blank' },
  { name: 'Toggle Switch', icon: 'mdi-toggle-switch' },
  { name: 'Dropdown', icon: 'mdi-menu-down' },

  // Miscellaneous
  { name: 'Bookmark', icon: 'mdi-bookmark' },
  { name: 'Attachment', icon: 'mdi-paperclip' },
  { name: 'Link', icon: 'mdi-link' },
  { name: 'Eye', icon: 'mdi-eye' },
  { name: 'Eye Off', icon: 'mdi-eye-off' },
  { name: 'Flashlight', icon: 'mdi-flashlight' },
  { name: 'Fingerprint', icon: 'mdi-fingerprint' },
  { name: 'Lightbulb', icon: 'mdi-lightbulb' },
  { name: 'Rocket', icon: 'mdi-rocket' },

  // Project Management
  { name: 'Kanban', icon: 'mdi-view-week' },
  { name: 'Gantt Chart', icon: 'mdi-chart-timeline' },
  { name: 'Task', icon: 'mdi-checkbox-marked-circle-outline' },
  { name: 'Milestone', icon: 'mdi-flag-checkered' },
  { name: 'Sprint', icon: 'mdi-run-fast' },
  { name: 'Project', icon: 'mdi-clipboard-outline' },
  { name: 'Backlog', icon: 'mdi-format-list-bulleted' },
  { name: 'Timeline', icon: 'mdi-timeline' },

  // Sales and CRM
  { name: 'Lead', icon: 'mdi-account-star' },
  { name: 'Opportunity', icon: 'mdi-trophy' },
  { name: 'Deal', icon: 'mdi-handshake' },
  { name: 'Pipeline', icon: 'mdi-pipe' },
  { name: 'Funnel', icon: 'mdi-filter' },
  { name: 'Contact', icon: 'mdi-card-account-details' },
  { name: 'Company', icon: 'mdi-domain' },
  { name: 'Sales Target', icon: 'mdi-target' },

  // Analytics and Reporting
  { name: 'Dashboard', icon: 'mdi-monitor-dashboard' },
  { name: 'Chart Bar', icon: 'mdi-chart-bar' },
  { name: 'Chart Line', icon: 'mdi-chart-line' },
  { name: 'Chart Pie', icon: 'mdi-chart-pie' },
  { name: 'Chart Donut', icon: 'mdi-chart-donut' },
  { name: 'Analytics', icon: 'mdi-google-analytics' },
  { name: 'Trend Up', icon: 'mdi-trending-up' },
  { name: 'Trend Down', icon: 'mdi-trending-down' },

  // Communication and Collaboration
  { name: 'Team', icon: 'mdi-account-group' },
  { name: 'Meeting', icon: 'mdi-video-account' },
  { name: 'Call', icon: 'mdi-phone-in-talk' },
  { name: 'Chat Bubble', icon: 'mdi-message-text' },
  { name: 'Forum', icon: 'mdi-forum' },
  { name: 'Comment', icon: 'mdi-comment' },
  { name: 'Feedback', icon: 'mdi-comment-quote' },
  { name: 'Share', icon: 'mdi-share' },

  // Document Management
  { name: 'Document', icon: 'mdi-file-document' },
  { name: 'Contract', icon: 'mdi-file-sign' },
  { name: 'Proposal', icon: 'mdi-file-presentation-box' },
  { name: 'Invoice', icon: 'mdi-file-chart' },
  { name: 'Signature', icon: 'mdi-draw' },

  // Time and Schedule
  { name: 'Calendar', icon: 'mdi-calendar' },
  { name: 'Stopwatch', icon: 'mdi-timer' },
  { name: 'Hourglass', icon: 'mdi-timer-sand' },
  { name: 'Schedule', icon: 'mdi-calendar-clock' },

  // Productivity and Tools
  { name: 'Note', icon: 'mdi-note-text' },
  { name: 'Checklist', icon: 'mdi-format-list-checks' },
  { name: 'Calculator', icon: 'mdi-calculator' },
  { name: 'Tools', icon: 'mdi-tools' },
  { name: 'Wrench', icon: 'mdi-wrench' },

  // Notifications and Alerts
  { name: 'Reminder', icon: 'mdi-alarm' },
  { name: 'Flag', icon: 'mdi-flag' },

  // Miscellaneous Business
  { name: 'Briefcase', icon: 'mdi-briefcase' },
  { name: 'Presentation', icon: 'mdi-presentation' },
  { name: 'Lightbulb', icon: 'mdi-lightbulb-on' },
];
