/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/[workspaceSlug]/card/[cardId]': RouteRecordInfo<'/[workspaceSlug]/card/[cardId]', '/:workspaceSlug/card/:cardId', { workspaceSlug: ParamValue<true>, cardId: ParamValue<true> }, { workspaceSlug: ParamValue<false>, cardId: ParamValue<false> }>,
    '/[workspaceSlug]/list/[listId]/': RouteRecordInfo<'/[workspaceSlug]/list/[listId]/', '/:workspaceSlug/list/:listId', { workspaceSlug: ParamValue<true>, listId: ParamValue<true> }, { workspaceSlug: ParamValue<false>, listId: ParamValue<false> }>,
    '/invite/[inviteCode]': RouteRecordInfo<'/invite/[inviteCode]', '/invite/:inviteCode', { inviteCode: ParamValue<true> }, { inviteCode: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/settings/[section]': RouteRecordInfo<'/settings/[section]', '/settings/:section', { section: ParamValue<true> }, { section: ParamValue<false> }>,
  }
}
